import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Splits CRM',
  description: 'Terms of Service for Splits CRM, a B2B SaaS platform for Independent Sales Organizations in the payments industry.',
}

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <Link href="/" className="text-emerald-600 hover:text-emerald-700 text-sm font-medium inline-flex items-center gap-1 mb-8">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" /></svg>
          Back to home
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: March 16, 2026</p>

        {/* 1. Definitions */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Definitions</h2>
          <p className="text-slate-600 leading-relaxed">
            In these Terms of Service (&ldquo;Terms&rdquo;), &ldquo;Service&rdquo; refers to the Splits CRM platform located at splitscrm.com, including all features, application programming interfaces, and related services. &ldquo;Customer&rdquo; refers to the business entity, typically an Independent Sales Organization (ISO), that subscribes to the Service. &ldquo;Authorized User&rdquo; means any individual who is granted access to the Service by a Customer. &ldquo;Customer Data&rdquo; means all data uploaded, entered, or generated by a Customer through the Service, including but not limited to merchant information, residual data, documents, and Social Security Numbers. &ldquo;AI Features&rdquo; refers to features powered by third-party artificial intelligence services, specifically Anthropic&rsquo;s Claude API, including PDF extraction, column mapping, and data normalization.
          </p>
        </section>

        {/* 2. Account Registration and Access */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Account Registration and Access</h2>
          <p className="text-slate-600 leading-relaxed">
            Accounts are created through Google OAuth or email and password registration. The Customer must provide accurate and complete company and contact information during registration. The Customer is responsible for managing all Authorized Users and their access levels within the platform, and is responsible for all activity that occurs under their account. Each organization is limited to one account, with sub-accounts for agents and partners managed within the platform. You must promptly notify us of any unauthorized use of your account or any other breach of security.
          </p>
        </section>

        {/* 3. License Grant and Restrictions */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">3. License Grant and Restrictions</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            Subject to these Terms, we grant you a non-exclusive, non-transferable, revocable license to access and use the Service during the term of your subscription. This license includes the right to upload, store, and process Customer Data through the Service in accordance with these Terms and our Privacy Policy.
          </p>
          <p className="text-slate-600 leading-relaxed">
            You may not reverse engineer, decompile, or disassemble the Service or any part thereof. You may not sublicense, resell, or redistribute access to the Service. You may not use the Service for any unlawful purpose or in violation of any applicable laws or regulations. You may not attempt to gain unauthorized access to other customers&rsquo; data or to any systems or networks connected to the Service. You may not circumvent any security measures, rate limits, or access controls implemented in the Service. You may not use automated means to scrape or extract data from the Service except through authorized APIs. You may not upload malicious code, viruses, or other harmful content.
          </p>
        </section>

        {/* 4. Customer Data Ownership and Responsibilities */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Customer Data Ownership and Responsibilities</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            The Customer retains all rights, title, and interest in and to Customer Data. We claim no ownership over Customer Data. By using the Service, you grant us a limited, non-exclusive license to use Customer Data solely for the purpose of providing and improving the Service.
          </p>
          <p className="text-slate-600 leading-relaxed">
            The Customer is solely responsible for the accuracy, quality, and legality of all Customer Data. The Customer represents and warrants that they have all necessary rights, consents, and legal authority to upload data to the Service, including Social Security Numbers, merchant personally identifiable information, and documents. The Customer is responsible for compliance with all applicable laws regarding the data they upload, including but not limited to the Gramm-Leach-Bliley Act and applicable state privacy laws. The Customer must promptly notify affected individuals and Splits CRM of any data breach originating from the Customer&rsquo;s systems.
          </p>
        </section>

        {/* 5. AI Features and Third-Party Processing */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">5. AI Features and Third-Party Processing</h2>
          <p className="text-slate-600 leading-relaxed">
            Certain features of the Service use Anthropic&rsquo;s Claude API to process Customer Data, including PDF extraction and column mapping. Data sent to Anthropic is governed by Anthropic&rsquo;s API Terms of Service and is not used for model training. AI outputs are provided &ldquo;as-is&rdquo; and may contain errors. The Customer is solely responsible for reviewing and verifying all AI-generated results before acting on them or incorporating them into business decisions. We do not guarantee the accuracy, completeness, or reliability of AI outputs. The Customer may not use AI features to process data that they are not authorized to share with third-party processors. Use of AI features constitutes consent to processing by Anthropic as described in our <Link href="/privacy" className="text-emerald-600 hover:text-emerald-700">Privacy Policy</Link>.
          </p>
        </section>

        {/* 6. Pricing, Billing, and Payment */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">6. Pricing, Billing, and Payment</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            The Service is offered through paid subscription plans starting at $99 per month, with pricing subject to change upon at least thirty (30) days&rsquo; written notice. A free trial period is available for new customers as described in Section 7. All fees are billed monthly in United States dollars. Fees are non-refundable except as required by applicable law.
          </p>
          <p className="text-slate-600 leading-relaxed">
            If we change our pricing, we will provide you with at least thirty (30) days&rsquo; written notice. You may cancel your subscription before the new pricing takes effect. Accounts with past-due balances may be suspended after fifteen (15) days of non-payment. We reserve the right to charge interest on overdue amounts at the rate of one and one-half percent (1.5%) per month or the maximum rate permitted by applicable law, whichever is lower.
          </p>
        </section>

        {/* 7. Free Trial */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Free Trial</h2>
          <p className="text-slate-600 leading-relaxed">
            We offer a fourteen (14) day free trial with full access to all features. No payment information is required to begin the trial. At the end of the trial period, you may subscribe to a paid plan to continue using the Service. If you do not subscribe, your account will be suspended and Customer Data will be retained for thirty (30) days after trial expiration, after which it will be permanently deleted. We reserve the right to modify or discontinue the trial program at any time without prior notice.
          </p>
        </section>

        {/* 8. Service Availability and Support */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Service Availability and Support</h2>
          <p className="text-slate-600 leading-relaxed">
            We use commercially reasonable efforts to maintain the availability of the Service. However, we do not guarantee any specific uptime percentage and do not offer a formal service level agreement at this time. Scheduled maintenance will be announced at least twenty-four (24) hours in advance when possible. We are not liable for any downtime or service interruptions caused by our third-party service providers, including Supabase, Vercel, Anthropic, or Google. Support is available via email at support@splitscrm.com during regular business hours.
          </p>
        </section>

        {/* 9. Data Security */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Data Security</h2>
          <p className="text-slate-600 leading-relaxed">
            We implement industry-standard security measures to protect Customer Data, as described in detail in our <Link href="/privacy" className="text-emerald-600 hover:text-emerald-700">Privacy Policy</Link>. These measures include encryption at rest and in transit for all Customer Data and row-level security ensuring strict data isolation between customers. In the event of a security breach affecting your data, we will notify you within seventy-two (72) hours of becoming aware of the breach. For complete information about our security practices, please refer to our Privacy Policy and Data Processing Agreement.
          </p>
        </section>

        {/* 10. Intellectual Property */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">10. Intellectual Property</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            Splits CRM retains all rights, title, and interest in and to the Service, including all software, algorithms, user interface and user experience design, documentation, and trademarks. This includes any improvements, modifications, or derivative works of the Service, as well as aggregated, anonymized insights derived from usage patterns, which do not include or identify Customer Data.
          </p>
          <p className="text-slate-600 leading-relaxed">
            The Customer retains all rights, title, and interest in all Customer Data and in the Customer&rsquo;s trademarks, branding, and proprietary business processes. If the Customer provides suggestions, ideas, or other feedback regarding the Service, we may use such feedback without obligation or compensation to the Customer.
          </p>
        </section>

        {/* 11. Confidentiality */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">11. Confidentiality</h2>
          <p className="text-slate-600 leading-relaxed">
            Each party agrees to protect the other party&rsquo;s Confidential Information with at least the same degree of care it uses to protect its own confidential information, and in no event less than reasonable care. Confidential Information includes Customer Data, pricing information, business plans, and technical details of the Service. Confidential Information does not include information that is publicly known through no fault of the receiving party, independently developed by the receiving party without reference to the disclosing party&rsquo;s Confidential Information, or received from a third party without restriction on disclosure. Confidentiality obligations under this section survive termination of these Terms for a period of three (3) years.
          </p>
        </section>

        {/* 12. Warranty Disclaimers */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">12. Warranty Disclaimers</h2>
          <p className="text-slate-600 leading-relaxed uppercase font-medium">
            The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. To the fullest extent permitted by applicable law, we disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or secure. AI features may produce inaccurate results, and the Customer assumes all risk arising from reliance on AI outputs. We do not warrant that residual calculations, data imports, or other financial computations performed by the Service will be accurate. The Customer must independently verify all financial data and calculations before relying on them for business decisions, agent compensation, or any other purpose.
          </p>
        </section>

        {/* 13. Limitation of Liability */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">13. Limitation of Liability</h2>
          <p className="text-slate-600 leading-relaxed">
            To the maximum extent permitted by applicable law, our total aggregate liability for all claims arising out of or related to these Terms or the Service shall not exceed the total fees paid by the Customer to Splits CRM during the twelve (12) months immediately preceding the event giving rise to the claim. In no event shall either party be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to lost profits, lost data, or business interruption, regardless of the cause of action or theory of liability, even if the party has been advised of the possibility of such damages. The foregoing limitations do not apply to breaches of confidentiality obligations, indemnification obligations, or willful misconduct or gross negligence.
          </p>
        </section>

        {/* 14. Indemnification */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">14. Indemnification</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            The Customer agrees to indemnify, defend, and hold harmless Splits CRM and its officers, directors, employees, and agents from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&rsquo; fees) arising out of or related to Customer Data, including without limitation claims related to unauthorized collection or use of Social Security Numbers, the Customer&rsquo;s violation of applicable laws or regulations, or the Customer&rsquo;s breach of these Terms.
          </p>
          <p className="text-slate-600 leading-relaxed">
            Splits CRM agrees to indemnify, defend, and hold harmless the Customer from and against claims that the Service infringes any third-party intellectual property rights, and from our breach of confidentiality or data security obligations. The indemnified party must promptly notify the indemnifying party of any claim. The indemnifying party shall have the right to control the defense and settlement of any such claim, and the indemnified party shall cooperate at the indemnifying party&rsquo;s expense.
          </p>
        </section>

        {/* 15. Termination */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">15. Termination</h2>
          <p className="text-slate-600 leading-relaxed mb-4">
            The Customer may cancel their subscription at any time through account settings or by providing written notice to support@splitscrm.com. No refund will be issued for partial months. Customer Data will be available for export for thirty (30) days following termination.
          </p>
          <p className="text-slate-600 leading-relaxed mb-4">
            We may terminate the Customer&rsquo;s account for material breach of these Terms upon thirty (30) days&rsquo; written notice and an opportunity to cure the breach. We may immediately suspend access to the Service for non-payment, security threats, illegal activity, or violation of the acceptable use restrictions in Section 3. We may discontinue the Service entirely upon ninety (90) days&rsquo; prior written notice.
          </p>
          <p className="text-slate-600 leading-relaxed">
            Upon termination, all licenses granted to the Customer under these Terms terminate immediately. Customer Data will be deleted thirty (30) days after termination unless returned to the Customer pursuant to the Data Processing Agreement. Provisions that by their nature should survive termination shall survive, including but not limited to confidentiality, limitation of liability, indemnification, and intellectual property provisions.
          </p>
        </section>

        {/* 16. Dispute Resolution */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">16. Dispute Resolution</h2>
          <p className="text-slate-600 leading-relaxed">
            These Terms shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of laws principles. Before initiating any formal legal proceedings, the parties agree to attempt to resolve any dispute informally for a period of thirty (30) days. Any dispute that cannot be resolved informally shall be brought exclusively in the state or federal courts located in the State of Florida, and each party consents to the exclusive jurisdiction and venue of such courts. The Customer agrees to resolve all disputes with Splits CRM on an individual basis and waives the right to participate in any class action or representative proceeding.
          </p>
        </section>

        {/* 17. Modifications to Terms */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">17. Modifications to Terms</h2>
          <p className="text-slate-600 leading-relaxed">
            We may modify these Terms from time to time. We will provide at least thirty (30) days&rsquo; written notice of any material changes by email. Your continued use of the Service after the effective date of a revised set of Terms constitutes your acceptance of the updated Terms. If you do not agree to the modified Terms, you may terminate your subscription before the effective date of the changes.
          </p>
        </section>

        {/* 18. General Provisions */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">18. General Provisions</h2>
          <p className="text-slate-600 leading-relaxed">
            These Terms, together with our <Link href="/privacy" className="text-emerald-600 hover:text-emerald-700">Privacy Policy</Link> and Data Processing Agreement, constitute the entire agreement between you and Splits CRM with respect to the Service and supersede all prior or contemporaneous agreements, understandings, or communications. If any provision of these Terms is found to be unenforceable, the remaining provisions shall continue in full force and effect. Our failure to enforce any provision of these Terms shall not constitute a waiver of that provision. The Customer may not assign these Terms or any rights hereunder without our prior written consent. We may assign these Terms in connection with a merger, acquisition, or sale of all or substantially all of our assets. Neither party shall be liable for any delay or failure to perform resulting from events beyond its reasonable control, including but not limited to natural disasters, acts of government, or failures of third-party services. All notices to the Customer will be sent to the email address on file. Notices to Splits CRM should be sent to support@splitscrm.com.
          </p>
        </section>

        {/* 19. Contact Information */}
        <section className="mb-10">
          <h2 className="text-xl font-semibold text-slate-900 mb-3">19. Contact Information</h2>
          <p className="text-slate-600 leading-relaxed">
            For legal inquiries or questions about these Terms, please contact us at <a href="mailto:support@splitscrm.com" className="text-emerald-600 hover:text-emerald-700">support@splitscrm.com</a>.
          </p>
        </section>

        <div className="border-t border-slate-200 pt-8 mt-12">
          <p className="text-slate-400 text-sm text-center">&copy; 2026 Splits CRM. All rights reserved.</p>
        </div>
      </div>
    </main>
  )
}
