export interface MCCCode {
  code: string;
  description: string;
  category: string;
  riskLevel?: 'high-risk' | 'restricted';
}

export const MCC_CODES: MCCCode[] = [
  // ============================================================
  // Agricultural Services (0001-1499)
  // ============================================================
  { code: '0742', description: 'Veterinary Services', category: 'Professional Services' },
  { code: '0763', description: 'Agricultural Cooperatives', category: 'Wholesale' },
  { code: '0780', description: 'Landscaping and Horticultural Services', category: 'Contractors' },

  // ============================================================
  // Contracted Services (1520-1799)
  // ============================================================
  { code: '1520', description: 'General Contractors - Residential and Commercial', category: 'Contractors' },
  { code: '1711', description: 'Heating, Plumbing, and Air Conditioning Contractors', category: 'Contractors' },
  { code: '1731', description: 'Electrical Contractors', category: 'Contractors' },
  { code: '1740', description: 'Masonry, Stonework, Tile Setting, Plastering, and Insulation Contractors', category: 'Contractors' },
  { code: '1750', description: 'Carpentry Contractors', category: 'Contractors' },
  { code: '1761', description: 'Roofing, Siding, and Sheet Metal Work Contractors', category: 'Contractors' },
  { code: '1771', description: 'Concrete Work Contractors', category: 'Contractors' },
  { code: '1799', description: 'Special Trade Contractors - Not Elsewhere Classified', category: 'Contractors' },

  // ============================================================
  // Airlines (3000-3350)
  // ============================================================
  { code: '3000', description: 'United Airlines', category: 'Airlines' },
  { code: '3001', description: 'American Airlines', category: 'Airlines' },
  { code: '3002', description: 'Pan American World Airways', category: 'Airlines' },
  { code: '3003', description: 'Eurofly', category: 'Airlines' },
  { code: '3004', description: 'Dragon Air', category: 'Airlines' },
  { code: '3005', description: 'British Airways', category: 'Airlines' },
  { code: '3006', description: 'Japan Airlines', category: 'Airlines' },
  { code: '3007', description: 'Air France', category: 'Airlines' },
  { code: '3008', description: 'Lufthansa', category: 'Airlines' },
  { code: '3009', description: 'Air Canada', category: 'Airlines' },
  { code: '3010', description: 'KLM Royal Dutch Airlines', category: 'Airlines' },
  { code: '3011', description: 'Aeroflot', category: 'Airlines' },
  { code: '3012', description: 'Qantas', category: 'Airlines' },
  { code: '3013', description: 'Alitalia', category: 'Airlines' },
  { code: '3014', description: 'Saudi Arabian Airlines', category: 'Airlines' },
  { code: '3015', description: 'Swiss International Air Lines', category: 'Airlines' },
  { code: '3016', description: 'SAS (Scandinavian Airlines)', category: 'Airlines' },
  { code: '3017', description: 'South African Airways', category: 'Airlines' },
  { code: '3018', description: 'Varig Brazilian Airlines', category: 'Airlines' },
  { code: '3019', description: 'Germanwings', category: 'Airlines' },
  { code: '3020', description: 'Air India', category: 'Airlines' },
  { code: '3021', description: 'Air Algerie', category: 'Airlines' },
  { code: '3022', description: 'Philippine Airlines', category: 'Airlines' },
  { code: '3023', description: 'Mexicana Airlines', category: 'Airlines' },
  { code: '3024', description: 'Pakistan International Airlines', category: 'Airlines' },
  { code: '3025', description: 'Air New Zealand', category: 'Airlines' },
  { code: '3026', description: 'Emirates', category: 'Airlines' },
  { code: '3027', description: 'Union de Transports Aeriens', category: 'Airlines' },
  { code: '3028', description: 'Air Malta', category: 'Airlines' },
  { code: '3029', description: 'Sabena Belgian World Airlines', category: 'Airlines' },
  { code: '3030', description: 'Aerolineas Argentinas', category: 'Airlines' },
  { code: '3031', description: 'Olympic Airways', category: 'Airlines' },
  { code: '3032', description: 'El Al Israel Airlines', category: 'Airlines' },
  { code: '3033', description: 'Ansett Airlines', category: 'Airlines' },
  { code: '3034', description: 'Etihad Airways', category: 'Airlines' },
  { code: '3035', description: 'TAP Air Portugal', category: 'Airlines' },
  { code: '3036', description: 'VASP (Viacao Aerea Sao Paulo)', category: 'Airlines' },
  { code: '3037', description: 'EgyptAir', category: 'Airlines' },
  { code: '3038', description: 'China Airlines', category: 'Airlines' },
  { code: '3039', description: 'Cathay Pacific', category: 'Airlines' },
  { code: '3040', description: 'Gulf Air', category: 'Airlines' },
  { code: '3041', description: 'Finnair', category: 'Airlines' },
  { code: '3042', description: 'Aer Lingus', category: 'Airlines' },
  { code: '3043', description: 'Air Lanka', category: 'Airlines' },
  { code: '3044', description: 'Air Pacific', category: 'Airlines' },
  { code: '3045', description: 'Avianca', category: 'Airlines' },
  { code: '3046', description: 'LACSA (Costa Rica)', category: 'Airlines' },
  { code: '3047', description: 'TACA International', category: 'Airlines' },
  { code: '3048', description: 'Royal Air Maroc', category: 'Airlines' },
  { code: '3049', description: 'Tunis Air', category: 'Airlines' },
  { code: '3050', description: 'Icelandair', category: 'Airlines' },
  { code: '3051', description: 'Austrian Airlines', category: 'Airlines' },
  { code: '3052', description: 'LAN Chile', category: 'Airlines' },
  { code: '3053', description: 'AVIACO (Spain)', category: 'Airlines' },
  { code: '3054', description: 'LADECO (Chile)', category: 'Airlines' },
  { code: '3055', description: 'LAB (Lloyd Aereo Boliviano)', category: 'Airlines' },
  { code: '3056', description: 'Asiana Airlines', category: 'Airlines' },
  { code: '3057', description: 'Turkish Airlines', category: 'Airlines' },
  { code: '3058', description: 'Copa Airlines', category: 'Airlines' },
  { code: '3059', description: 'ACES (Colombia)', category: 'Airlines' },
  { code: '3060', description: 'Southwest Airlines', category: 'Airlines' },
  { code: '3061', description: 'All Nippon Airways (ANA)', category: 'Airlines' },
  { code: '3062', description: 'Aloha Airlines', category: 'Airlines' },
  { code: '3063', description: 'Total Air (Cameroon)', category: 'Airlines' },
  { code: '3064', description: 'Reno Air', category: 'Airlines' },
  { code: '3065', description: 'Liat Airlines', category: 'Airlines' },
  { code: '3066', description: 'Air Europa', category: 'Airlines' },
  { code: '3067', description: 'Condor', category: 'Airlines' },
  { code: '3068', description: 'Air Seychelles', category: 'Airlines' },
  { code: '3069', description: 'Sun Country Airlines', category: 'Airlines' },
  { code: '3070', description: 'Westjet', category: 'Airlines' },
  { code: '3071', description: 'Air British Columbia', category: 'Airlines' },
  { code: '3072', description: 'Korean Air', category: 'Airlines' },
  { code: '3073', description: 'Air Dolomiti', category: 'Airlines' },
  { code: '3074', description: 'Biman Bangladesh Airlines', category: 'Airlines' },
  { code: '3075', description: 'Singapore Airlines', category: 'Airlines' },
  { code: '3076', description: 'Aeromexico', category: 'Airlines' },
  { code: '3077', description: 'Thai Airways', category: 'Airlines' },
  { code: '3078', description: 'China Eastern Airlines', category: 'Airlines' },
  { code: '3079', description: 'Jet Airways', category: 'Airlines' },
  { code: '3080', description: 'Air Zimbabwe', category: 'Airlines' },
  { code: '3081', description: 'Nordwind Airlines', category: 'Airlines' },
  { code: '3082', description: 'Korean Air', category: 'Airlines' },
  { code: '3083', description: 'Cayman Airways', category: 'Airlines' },
  { code: '3084', description: 'Eva Air', category: 'Airlines' },
  { code: '3085', description: 'Midwest Express Airlines', category: 'Airlines' },
  { code: '3086', description: 'Carnival Air', category: 'Airlines' },
  { code: '3087', description: 'Metro Airlines', category: 'Airlines' },
  { code: '3088', description: 'Croatia Airlines', category: 'Airlines' },
  { code: '3089', description: 'Transaero', category: 'Airlines' },
  { code: '3090', description: 'Uzbekistan Airways', category: 'Airlines' },
  { code: '3091', description: 'Austrian Air Services', category: 'Airlines' },
  { code: '3092', description: 'Caribbean Airlines (BWIA)', category: 'Airlines' },
  { code: '3093', description: 'Comair', category: 'Airlines' },
  { code: '3094', description: 'Zambia Airways', category: 'Airlines' },
  { code: '3095', description: 'AirTran Airways', category: 'Airlines' },
  { code: '3096', description: 'Air Zimbabwe', category: 'Airlines' },
  { code: '3097', description: 'Spanair', category: 'Airlines' },
  { code: '3098', description: 'Aserca Airlines', category: 'Airlines' },
  { code: '3099', description: 'Cathay Pacific', category: 'Airlines' },
  { code: '3100', description: 'Malaysian Airlines', category: 'Airlines' },
  { code: '3102', description: 'Iberia Airlines', category: 'Airlines' },
  { code: '3103', description: 'Garuda Indonesia', category: 'Airlines' },
  { code: '3106', description: 'Braathens SAFE', category: 'Airlines' },
  { code: '3110', description: 'Wings Airways', category: 'Airlines' },
  { code: '3111', description: 'British Midland', category: 'Airlines' },
  { code: '3112', description: 'Windward Islands Airways', category: 'Airlines' },
  { code: '3115', description: 'Tower Air', category: 'Airlines' },
  { code: '3117', description: 'Viasa', category: 'Airlines' },
  { code: '3118', description: 'Valley Airlines', category: 'Airlines' },
  { code: '3125', description: 'Tan Honduras', category: 'Airlines' },
  { code: '3126', description: 'TAM Airlines', category: 'Airlines' },
  { code: '3127', description: 'TranBrasil Airlines', category: 'Airlines' },
  { code: '3129', description: 'Surinam Airways', category: 'Airlines' },
  { code: '3130', description: 'Sunworld International', category: 'Airlines' },
  { code: '3131', description: 'VLM Airlines', category: 'Airlines' },
  { code: '3132', description: 'Frontier Airlines', category: 'Airlines' },
  { code: '3133', description: 'Sunbelt Airlines', category: 'Airlines' },
  { code: '3135', description: 'Sudan Airways', category: 'Airlines' },
  { code: '3136', description: 'Qatar Airways', category: 'Airlines' },
  { code: '3137', description: 'Singleton', category: 'Airlines' },
  { code: '3138', description: 'Simmons Airlines', category: 'Airlines' },
  { code: '3143', description: 'Scenic Airlines', category: 'Airlines' },
  { code: '3144', description: 'Virgin Atlantic', category: 'Airlines' },
  { code: '3145', description: 'San Juan Airlines', category: 'Airlines' },
  { code: '3146', description: 'Luxair', category: 'Airlines' },
  { code: '3148', description: 'Air Littoral', category: 'Airlines' },
  { code: '3151', description: 'Air Zaire', category: 'Airlines' },
  { code: '3154', description: 'Princeville Airways', category: 'Airlines' },
  { code: '3156', description: 'Go Fly', category: 'Airlines' },
  { code: '3159', description: 'PGA-Portugalia Airlines', category: 'Airlines' },
  { code: '3161', description: 'All Nippon Airways', category: 'Airlines' },
  { code: '3164', description: 'Norontair', category: 'Airlines' },
  { code: '3165', description: 'New York Helicopter', category: 'Airlines' },
  { code: '3167', description: 'Aero Continente', category: 'Airlines' },
  { code: '3170', description: 'Mount Cook Airlines', category: 'Airlines' },
  { code: '3171', description: 'Canadian Airlines International', category: 'Airlines' },
  { code: '3172', description: 'Nation Air', category: 'Airlines' },
  { code: '3174', description: 'Jetblue Airways', category: 'Airlines' },
  { code: '3175', description: 'Middle East Air', category: 'Airlines' },
  { code: '3176', description: 'Metroflight Airlines', category: 'Airlines' },
  { code: '3177', description: 'AirAsia', category: 'Airlines' },
  { code: '3178', description: 'Mesa Air', category: 'Airlines' },
  { code: '3180', description: 'Westcoast Energy', category: 'Airlines' },
  { code: '3181', description: 'Malev Hungarian Airlines', category: 'Airlines' },
  { code: '3182', description: 'LOT Polish Airlines', category: 'Airlines' },
  { code: '3183', description: 'Adria Airways', category: 'Airlines' },
  { code: '3184', description: 'Linjeflyg', category: 'Airlines' },
  { code: '3185', description: 'LAV (Venezuela)', category: 'Airlines' },
  { code: '3186', description: 'LAP (Paraguay)', category: 'Airlines' },
  { code: '3187', description: 'LACSA (Costa Rica)', category: 'Airlines' },
  { code: '3188', description: 'Inex Adria Aviopromet', category: 'Airlines' },
  { code: '3190', description: 'Jugoslovenski Aerotransport (JAT)', category: 'Airlines' },
  { code: '3191', description: 'Island Airlines', category: 'Airlines' },
  { code: '3192', description: 'Iran Air', category: 'Airlines' },
  { code: '3193', description: 'Indian Airlines', category: 'Airlines' },
  { code: '3196', description: 'Hawaiian Airlines', category: 'Airlines' },
  { code: '3197', description: 'Havasu Airlines', category: 'Airlines' },
  { code: '3200', description: 'Fuji Air', category: 'Airlines' },
  { code: '3203', description: 'Golden Pacific Air', category: 'Airlines' },
  { code: '3204', description: 'Freedom Air', category: 'Airlines' },
  { code: '3206', description: 'China Southern Airlines', category: 'Airlines' },
  { code: '3211', description: 'Norwegian Air Shuttle', category: 'Airlines' },
  { code: '3212', description: 'Dominicana Airlines', category: 'Airlines' },
  { code: '3213', description: 'Malmo Aviation', category: 'Airlines' },
  { code: '3215', description: 'Dan Air Services', category: 'Airlines' },
  { code: '3216', description: 'Cumberland Airlines', category: 'Airlines' },
  { code: '3217', description: 'CSA (Czech Airlines)', category: 'Airlines' },
  { code: '3218', description: 'Crown Air', category: 'Airlines' },
  { code: '3219', description: 'Copa Airlines', category: 'Airlines' },
  { code: '3220', description: 'Compania Faucett', category: 'Airlines' },
  { code: '3221', description: 'Transportes Aereos Nacionales (Colombia)', category: 'Airlines' },
  { code: '3222', description: 'Comandatuba Air Taxi', category: 'Airlines' },
  { code: '3223', description: 'Comair', category: 'Airlines' },
  { code: '3226', description: 'Delta Air Lines', category: 'Airlines' },
  { code: '3228', description: 'Bahamasair', category: 'Airlines' },
  { code: '3229', description: 'Saeta (Ecuador)', category: 'Airlines' },
  { code: '3231', description: 'SAHSA (Honduras)', category: 'Airlines' },
  { code: '3233', description: 'Capitol Air', category: 'Airlines' },
  { code: '3234', description: 'Caribbean Air Transport', category: 'Airlines' },
  { code: '3235', description: 'Brockway Air', category: 'Airlines' },
  { code: '3236', description: 'Air Bourbon', category: 'Airlines' },
  { code: '3238', description: 'Bemidji Airlines', category: 'Airlines' },
  { code: '3239', description: 'Bar Harbor Airlines', category: 'Airlines' },
  { code: '3240', description: 'Balair', category: 'Airlines' },
  { code: '3241', description: 'Aviateca (Guatemala)', category: 'Airlines' },
  { code: '3242', description: 'Avensa', category: 'Airlines' },
  { code: '3243', description: 'Austrian Airlines', category: 'Airlines' },
  { code: '3244', description: 'Piedmont Airlines', category: 'Airlines' },
  { code: '3245', description: 'Alia (Royal Jordanian)', category: 'Airlines' },
  { code: '3246', description: 'Alaska Airlines', category: 'Airlines' },
  { code: '3247', description: 'Airlines of Tasmania', category: 'Airlines' },
  { code: '3248', description: 'Air Zimbabwe', category: 'Airlines' },
  { code: '3251', description: 'Aloha Airlines', category: 'Airlines' },
  { code: '3252', description: 'ALM Antillean Airlines', category: 'Airlines' },
  { code: '3253', description: 'America West Airlines', category: 'Airlines' },
  { code: '3254', description: 'Trump Shuttle', category: 'Airlines' },
  { code: '3256', description: 'Alaska Airlines', category: 'Airlines' },
  { code: '3259', description: 'American Trans Air', category: 'Airlines' },
  { code: '3260', description: 'Spirit Airlines', category: 'Airlines' },
  { code: '3261', description: 'Air China', category: 'Airlines' },
  { code: '3262', description: 'Reno Air', category: 'Airlines' },
  { code: '3263', description: 'Aero Star', category: 'Airlines' },
  { code: '3266', description: 'Air Seychelles', category: 'Airlines' },
  { code: '3267', description: 'Air Panama', category: 'Airlines' },
  { code: '3280', description: 'Air Jamaica', category: 'Airlines' },
  { code: '3282', description: 'Air Djibouti', category: 'Airlines' },
  { code: '3284', description: 'Aero Virgin Islands', category: 'Airlines' },
  { code: '3285', description: 'Aero Peru', category: 'Airlines' },
  { code: '3286', description: 'Aerolineas Nicaraguenses', category: 'Airlines' },
  { code: '3287', description: 'Aero Coach Aviation', category: 'Airlines' },
  { code: '3292', description: 'Cyprus Airways', category: 'Airlines' },
  { code: '3293', description: 'Ecuatoriana', category: 'Airlines' },
  { code: '3294', description: 'Ethiopian Airlines', category: 'Airlines' },
  { code: '3295', description: 'Kenya Airways', category: 'Airlines' },
  { code: '3296', description: 'Air Berlin', category: 'Airlines' },
  { code: '3297', description: 'Tarom Romanian Air Transport', category: 'Airlines' },
  { code: '3298', description: 'Air Mauritius', category: 'Airlines' },
  { code: '3299', description: 'Wideroe Airlines', category: 'Airlines' },
  { code: '3300', description: 'Piedmont Airlines', category: 'Airlines' },
  { code: '3301', description: 'Comair', category: 'Airlines' },
  { code: '3350', description: 'Airline - Not Elsewhere Classified', category: 'Airlines' },

  // ============================================================
  // Car Rental (3351-3500)
  // ============================================================
  { code: '3351', description: 'Affiliated Auto Rental', category: 'Auto' },
  { code: '3352', description: 'American International Rent-A-Car', category: 'Auto' },
  { code: '3353', description: 'Brooks Rent-A-Car', category: 'Auto' },
  { code: '3354', description: 'Action Auto Rental', category: 'Auto' },
  { code: '3355', description: 'Sixt Car Rental', category: 'Auto' },
  { code: '3356', description: 'Avis Rent-A-Car', category: 'Auto' },
  { code: '3357', description: 'Hertz Rent-A-Car', category: 'Auto' },
  { code: '3359', description: 'Payless Car Rental', category: 'Auto' },
  { code: '3360', description: 'Snappy Car Rental', category: 'Auto' },
  { code: '3361', description: 'Airways Rent-A-Car', category: 'Auto' },
  { code: '3362', description: 'Altra Auto Rental', category: 'Auto' },
  { code: '3364', description: 'Agency Rent-A-Car', category: 'Auto' },
  { code: '3366', description: 'Budget Rent-A-Car', category: 'Auto' },
  { code: '3368', description: 'Holiday Rent-A-Car', category: 'Auto' },
  { code: '3370', description: 'Rent-A-Wreck', category: 'Auto' },
  { code: '3374', description: 'Accent Rent-A-Car', category: 'Auto' },
  { code: '3376', description: 'Ajax Rent-A-Car', category: 'Auto' },
  { code: '3380', description: 'Triangle Rent-A-Car', category: 'Auto' },
  { code: '3381', description: 'Europcar', category: 'Auto' },
  { code: '3385', description: 'Tropical Rent-A-Car', category: 'Auto' },
  { code: '3386', description: 'Showcase Rental Cars', category: 'Auto' },
  { code: '3387', description: 'Alamo Rent-A-Car', category: 'Auto' },
  { code: '3388', description: 'Merchants Rent-A-Car', category: 'Auto' },
  { code: '3389', description: 'Avis Rent-A-Car', category: 'Auto' },
  { code: '3390', description: 'Dollar Rent-A-Car', category: 'Auto' },
  { code: '3391', description: 'Europe By Car', category: 'Auto' },
  { code: '3393', description: 'National Car Rental', category: 'Auto' },
  { code: '3394', description: 'Kemwell Group Rent-A-Car', category: 'Auto' },
  { code: '3395', description: 'Thrifty Car Rental', category: 'Auto' },
  { code: '3396', description: 'Tilden Rent-A-Car', category: 'Auto' },
  { code: '3398', description: 'Econo-Car Rent-A-Car', category: 'Auto' },
  { code: '3400', description: 'Auto Host Car Rental', category: 'Auto' },
  { code: '3405', description: 'Enterprise Rent-A-Car', category: 'Auto' },
  { code: '3409', description: 'General Rent-A-Car', category: 'Auto' },
  { code: '3412', description: 'A-1 Rent-A-Car', category: 'Auto' },
  { code: '3414', description: 'Godfrey National Rent-A-Car', category: 'Auto' },
  { code: '3420', description: 'Ansa International Rent-A-Car', category: 'Auto' },
  { code: '3421', description: 'Allstate Rent-A-Car', category: 'Auto' },
  { code: '3423', description: 'Avcar Rent-A-Car', category: 'Auto' },
  { code: '3425', description: 'Automate Rent-A-Car', category: 'Auto' },
  { code: '3427', description: 'Avon Rent-A-Car', category: 'Auto' },
  { code: '3428', description: 'Carey Rent-A-Car', category: 'Auto' },
  { code: '3429', description: 'Insurance Rent-A-Car', category: 'Auto' },
  { code: '3430', description: 'Major Rent-A-Car', category: 'Auto' },
  { code: '3431', description: 'Replacement Rent-A-Car', category: 'Auto' },
  { code: '3432', description: 'Reserve Rent-A-Car', category: 'Auto' },
  { code: '3433', description: 'Ugly Duckling Rent-A-Car', category: 'Auto' },
  { code: '3434', description: 'USA Rent-A-Car', category: 'Auto' },
  { code: '3435', description: 'Value Rent-A-Car', category: 'Auto' },
  { code: '3436', description: 'Autoscope Rent-A-Car', category: 'Auto' },
  { code: '3437', description: 'Fox Rent-A-Car', category: 'Auto' },
  { code: '3438', description: 'Imagination Rent-A-Car (Priceless)', category: 'Auto' },
  { code: '3439', description: 'International Rent-A-Car', category: 'Auto' },
  { code: '3441', description: 'Advantage Rent-A-Car', category: 'Auto' },
  { code: '3501', description: 'Car Rental - Not Elsewhere Classified', category: 'Auto' },

  // ============================================================
  // Hotels/Lodging (3501-3999)
  // ============================================================
  { code: '3502', description: 'Holiday Inns', category: 'Hotels' },
  { code: '3503', description: 'Best Western', category: 'Hotels' },
  { code: '3504', description: 'Sheraton', category: 'Hotels' },
  { code: '3505', description: 'Hilton Hotels', category: 'Hotels' },
  { code: '3506', description: 'Forte Hotels', category: 'Hotels' },
  { code: '3507', description: 'Marriott', category: 'Hotels' },
  { code: '3508', description: 'Travelodge', category: 'Hotels' },
  { code: '3509', description: 'Colonnade Hotels', category: 'Hotels' },
  { code: '3510', description: 'Wyndham Hotels', category: 'Hotels' },
  { code: '3511', description: 'Days Inn', category: 'Hotels' },
  { code: '3512', description: 'Arabella Hotels', category: 'Hotels' },
  { code: '3513', description: 'Ramada Inns', category: 'Hotels' },
  { code: '3514', description: 'Renaissance Hotels', category: 'Hotels' },
  { code: '3515', description: 'Rodeway Inns', category: 'Hotels' },
  { code: '3516', description: 'La Quinta Motor Inns', category: 'Hotels' },
  { code: '3517', description: 'Americana Hotels', category: 'Hotels' },
  { code: '3518', description: 'Sol Hotels', category: 'Hotels' },
  { code: '3519', description: 'Pullman International Hotels', category: 'Hotels' },
  { code: '3520', description: 'Meridien Hotels', category: 'Hotels' },
  { code: '3521', description: 'Crest Hotels (United Kingdom)', category: 'Hotels' },
  { code: '3522', description: 'Tokyo Hotel', category: 'Hotels' },
  { code: '3523', description: 'Pennsula Hotels', category: 'Hotels' },
  { code: '3524', description: 'Welcome Group Hotels', category: 'Hotels' },
  { code: '3525', description: 'Dunfey Hotels', category: 'Hotels' },
  { code: '3526', description: 'Prince Hotels', category: 'Hotels' },
  { code: '3527', description: 'Downtowner Motor Inns', category: 'Hotels' },
  { code: '3528', description: 'Red Lion Hotels', category: 'Hotels' },
  { code: '3529', description: 'CP Hotels', category: 'Hotels' },
  { code: '3530', description: 'Renaissance Hotels and Resorts', category: 'Hotels' },
  { code: '3531', description: 'Kauai Coconut Beach Resort', category: 'Hotels' },
  { code: '3532', description: 'Royal Kona Resort', category: 'Hotels' },
  { code: '3533', description: 'Hotel Ibis', category: 'Hotels' },
  { code: '3534', description: 'Southern Pacific Hotels', category: 'Hotels' },
  { code: '3535', description: 'Hilton International', category: 'Hotels' },
  { code: '3536', description: 'Amfac Hotels', category: 'Hotels' },
  { code: '3537', description: 'ANA Hotels', category: 'Hotels' },
  { code: '3538', description: 'Concorde Hotels', category: 'Hotels' },
  { code: '3539', description: 'Summerfield Suites Hotels', category: 'Hotels' },
  { code: '3540', description: 'Iberotel Hotels', category: 'Hotels' },
  { code: '3541', description: 'Hotel Okura', category: 'Hotels' },
  { code: '3542', description: 'Royal Hotels', category: 'Hotels' },
  { code: '3543', description: 'Four Seasons Hotels', category: 'Hotels' },
  { code: '3544', description: 'Ciga Hotels', category: 'Hotels' },
  { code: '3545', description: 'Shangri-La Hotels', category: 'Hotels' },
  { code: '3546', description: 'Hotel Sierra', category: 'Hotels' },
  { code: '3548', description: 'Hoteles Melia', category: 'Hotels' },
  { code: '3549', description: 'Auberge des Gouverneurs', category: 'Hotels' },
  { code: '3550', description: 'Regal Hotels', category: 'Hotels' },
  { code: '3551', description: 'Mirage Hotel and Casino', category: 'Hotels' },
  { code: '3552', description: 'Coast Hotels', category: 'Hotels' },
  { code: '3553', description: 'Park Inns International', category: 'Hotels' },
  { code: '3554', description: 'Pinehurst Resort', category: 'Hotels' },
  { code: '3555', description: 'Treasure Island Hotel and Casino', category: 'Hotels' },
  { code: '3556', description: 'Barton Creek Resort', category: 'Hotels' },
  { code: '3557', description: 'Manhattan East Suite Hotels', category: 'Hotels' },
  { code: '3558', description: 'Jolly Hotels', category: 'Hotels' },
  { code: '3559', description: 'Candlewood Suites', category: 'Hotels' },
  { code: '3560', description: 'Aston Hotels', category: 'Hotels' },
  { code: '3561', description: 'Clubhouse Inns', category: 'Hotels' },
  { code: '3562', description: 'Quality Inns', category: 'Hotels' },
  { code: '3563', description: 'Comfort Inns', category: 'Hotels' },
  { code: '3564', description: 'Journey\'s End Motels', category: 'Hotels' },
  { code: '3565', description: 'Sam\'s Town Hotel and Casino', category: 'Hotels' },
  { code: '3566', description: 'Relax Inns', category: 'Hotels' },
  { code: '3567', description: 'Garden Place Hotel', category: 'Hotels' },
  { code: '3568', description: 'Soho Grand Hotel', category: 'Hotels' },
  { code: '3569', description: 'Ladbroke Hotels', category: 'Hotels' },
  { code: '3570', description: 'Forum Hotels', category: 'Hotels' },
  { code: '3571', description: 'Grand Wailea Resort', category: 'Hotels' },
  { code: '3572', description: 'Miyako Hotels', category: 'Hotels' },
  { code: '3573', description: 'Sandman Hotels', category: 'Hotels' },
  { code: '3574', description: 'Venture Inns', category: 'Hotels' },
  { code: '3575', description: 'Vagabond Hotels', category: 'Hotels' },
  { code: '3576', description: 'La Quinta Resorts', category: 'Hotels' },
  { code: '3577', description: 'Mandarin Oriental Hotels', category: 'Hotels' },
  { code: '3578', description: 'Frankenmuth Bavarian', category: 'Hotels' },
  { code: '3579', description: 'Hotel Mercure', category: 'Hotels' },
  { code: '3580', description: 'Hotel Del Coronado', category: 'Hotels' },
  { code: '3581', description: 'Delta Hotels', category: 'Hotels' },
  { code: '3582', description: 'California Hotel and Casino', category: 'Hotels' },
  { code: '3583', description: 'Radisson Hotels', category: 'Hotels' },
  { code: '3584', description: 'Princess Hotels International', category: 'Hotels' },
  { code: '3585', description: 'Hungar Hotels', category: 'Hotels' },
  { code: '3586', description: 'Sokos Hotels', category: 'Hotels' },
  { code: '3587', description: 'Doral Hotels', category: 'Hotels' },
  { code: '3588', description: 'Helmsley Hotels', category: 'Hotels' },
  { code: '3589', description: 'Doral Golf Resort', category: 'Hotels' },
  { code: '3590', description: 'Fairmont Hotels', category: 'Hotels' },
  { code: '3591', description: 'Sonesta Hotels', category: 'Hotels' },
  { code: '3592', description: 'Omni Hotels', category: 'Hotels' },
  { code: '3593', description: 'Cunard Hotels', category: 'Hotels' },
  { code: '3594', description: 'Arizona Biltmore', category: 'Hotels' },
  { code: '3595', description: 'Hospitality Inns', category: 'Hotels' },
  { code: '3596', description: 'Wynn Las Vegas', category: 'Hotels' },
  { code: '3597', description: 'Riverside Resort Hotel and Casino', category: 'Hotels' },
  { code: '3598', description: 'Regent International Hotels', category: 'Hotels' },
  { code: '3599', description: 'Pannonia Hotels', category: 'Hotels' },
  { code: '3600', description: 'Saddlebrook Resort', category: 'Hotels' },
  { code: '3601', description: 'Tradewinds Resort', category: 'Hotels' },
  { code: '3603', description: 'Noah\'s Hotels', category: 'Hotels' },
  { code: '3604', description: 'Hilton Garden Inn', category: 'Hotels' },
  { code: '3607', description: 'Fontainebleau Resorts', category: 'Hotels' },
  { code: '3609', description: 'Gaylord Opryland', category: 'Hotels' },
  { code: '3612', description: 'Movenpick Hotels', category: 'Hotels' },
  { code: '3613', description: 'Microtel Inns and Suites', category: 'Hotels' },
  { code: '3615', description: 'Extended Stay America', category: 'Hotels' },
  { code: '3617', description: 'Crown Plaza Hotels', category: 'Hotels' },
  { code: '3618', description: 'Loews Hotels', category: 'Hotels' },
  { code: '3619', description: 'Servico Hotels', category: 'Hotels' },
  { code: '3620', description: 'Forum Hotels', category: 'Hotels' },
  { code: '3621', description: 'Caesar\'s Palace', category: 'Hotels' },
  { code: '3622', description: 'Cabo Hotel', category: 'Hotels' },
  { code: '3623', description: 'Club Med', category: 'Hotels' },
  { code: '3625', description: 'Grand Hyatt', category: 'Hotels' },
  { code: '3626', description: 'Hotel Marisposa', category: 'Hotels' },
  { code: '3627', description: 'Residence Inns', category: 'Hotels' },
  { code: '3628', description: 'Ticaret Hotels', category: 'Hotels' },
  { code: '3629', description: 'New Otani Hotel', category: 'Hotels' },
  { code: '3630', description: 'NH Hotels', category: 'Hotels' },
  { code: '3631', description: 'Sleep Inns', category: 'Hotels' },
  { code: '3632', description: 'The Bulfinch Hotel', category: 'Hotels' },
  { code: '3633', description: 'Classic Custom Vacations', category: 'Hotels' },
  { code: '3634', description: 'Cambridge Suites', category: 'Hotels' },
  { code: '3635', description: 'Rixos Hotels', category: 'Hotels' },
  { code: '3637', description: 'Ramada Plaza', category: 'Hotels' },
  { code: '3638', description: 'Hotel Belair', category: 'Hotels' },
  { code: '3639', description: 'Hotel Marisposa', category: 'Hotels' },
  { code: '3640', description: 'MGM Grand Hotel', category: 'Hotels' },
  { code: '3641', description: 'Millennium Hotels', category: 'Hotels' },
  { code: '3642', description: 'Club Mediterranee', category: 'Hotels' },
  { code: '3643', description: 'Biltmore Hotels', category: 'Hotels' },
  { code: '3644', description: 'Bacara Resort', category: 'Hotels' },
  { code: '3645', description: 'Primadonna Hotel and Casino', category: 'Hotels' },
  { code: '3646', description: 'Renaissance Hotels', category: 'Hotels' },
  { code: '3647', description: 'Boutique Hotels', category: 'Hotels' },
  { code: '3648', description: 'AC Hotels by Marriott', category: 'Hotels' },
  { code: '3649', description: 'Hilton Garden Inns', category: 'Hotels' },
  { code: '3650', description: 'Hampton Inns', category: 'Hotels' },
  { code: '3651', description: 'Homewood Suites', category: 'Hotels' },
  { code: '3652', description: 'Peabody Hotels', category: 'Hotels' },
  { code: '3653', description: 'Greenbriar Resort', category: 'Hotels' },
  { code: '3654', description: 'Bob Baker Enterprises', category: 'Hotels' },
  { code: '3655', description: 'Doubletree', category: 'Hotels' },
  { code: '3656', description: 'Red Roof Inns', category: 'Hotels' },
  { code: '3657', description: 'Masters Economy Inns', category: 'Hotels' },
  { code: '3658', description: 'Econo Lodges', category: 'Hotels' },
  { code: '3659', description: 'Courtyard by Marriott', category: 'Hotels' },
  { code: '3660', description: 'Embassy Suites', category: 'Hotels' },
  { code: '3661', description: 'Virgin Hotels', category: 'Hotels' },
  { code: '3662', description: 'Comfort Suites', category: 'Hotels' },
  { code: '3663', description: 'Crown Sterling Suites', category: 'Hotels' },
  { code: '3664', description: 'Homestead Studio Suites', category: 'Hotels' },
  { code: '3665', description: 'Luxor Hotel and Casino', category: 'Hotels' },
  { code: '3666', description: 'Amerihost Inns', category: 'Hotels' },
  { code: '3667', description: 'Amerisuites', category: 'Hotels' },
  { code: '3668', description: 'Homegate Studios and Suites', category: 'Hotels' },
  { code: '3669', description: 'Hawthorn Suites', category: 'Hotels' },
  { code: '3670', description: 'Motel 6', category: 'Hotels' },
  { code: '3671', description: 'La Mansion del Rio', category: 'Hotels' },
  { code: '3672', description: 'Studio Plus', category: 'Hotels' },
  { code: '3673', description: 'MainStay Suites', category: 'Hotels' },
  { code: '3674', description: 'Oxford Suites', category: 'Hotels' },
  { code: '3675', description: 'TownePlace Suites', category: 'Hotels' },
  { code: '3676', description: 'Hyatt', category: 'Hotels' },
  { code: '3677', description: 'Staybridge Suites', category: 'Hotels' },
  { code: '3678', description: 'W Hotels', category: 'Hotels' },
  { code: '3679', description: 'Hotel Indigo', category: 'Hotels' },
  { code: '3680', description: 'Value Place', category: 'Hotels' },
  { code: '3681', description: 'Hotel Sierra', category: 'Hotels' },
  { code: '3682', description: 'Aloft Hotels', category: 'Hotels' },
  { code: '3683', description: 'Even Hotels', category: 'Hotels' },
  { code: '3684', description: 'Canadas Best Value Inn', category: 'Hotels' },
  { code: '3685', description: 'Americas Best Value Inn', category: 'Hotels' },
  { code: '3686', description: 'Rosen Hotels', category: 'Hotels' },
  { code: '3687', description: 'Hyatt Place', category: 'Hotels' },
  { code: '3688', description: 'Drury Inn', category: 'Hotels' },
  { code: '3689', description: 'Element Hotels', category: 'Hotels' },
  { code: '3690', description: 'Kimpton Hotels', category: 'Hotels' },
  { code: '3691', description: 'Whala Hotels', category: 'Hotels' },
  { code: '3692', description: 'Pullman Hotels', category: 'Hotels' },
  { code: '3693', description: 'Novotel Hotels', category: 'Hotels' },
  { code: '3694', description: 'Park Hyatt', category: 'Hotels' },
  { code: '3695', description: 'Andaz', category: 'Hotels' },
  { code: '3696', description: 'Autograph Collection', category: 'Hotels' },
  { code: '3697', description: 'Ascend Collection', category: 'Hotels' },
  { code: '3698', description: 'Cambria Hotels', category: 'Hotels' },
  { code: '3699', description: 'Curio Collection by Hilton', category: 'Hotels' },
  { code: '3700', description: 'Tru by Hilton', category: 'Hotels' },
  { code: '3750', description: 'Canopy by Hilton', category: 'Hotels' },
  { code: '3800', description: 'Tapestry Collection by Hilton', category: 'Hotels' },
  { code: '3816', description: 'Home2 Suites by Hilton', category: 'Hotels' },
  { code: '3835', description: 'Motto by Hilton', category: 'Hotels' },
  { code: '3900', description: 'Tempo by Hilton', category: 'Hotels' },
  { code: '3999', description: 'Hotel/Motel - Not Elsewhere Classified', category: 'Hotels' },

  // ============================================================
  // Transportation (4011-4789)
  // ============================================================
  { code: '4011', description: 'Railroads', category: 'Transportation' },
  { code: '4111', description: 'Local and Suburban Commuter Passenger Transportation', category: 'Transportation' },
  { code: '4112', description: 'Passenger Railways', category: 'Transportation' },
  { code: '4119', description: 'Ambulance Services', category: 'Transportation' },
  { code: '4121', description: 'Taxicabs and Rideshares', category: 'Transportation' },
  { code: '4131', description: 'Bus Lines', category: 'Transportation' },
  { code: '4214', description: 'Motor Freight Carriers and Trucking', category: 'Transportation' },
  { code: '4215', description: 'Courier Services - Air and Ground', category: 'Transportation' },
  { code: '4225', description: 'Public Warehousing and Storage', category: 'Transportation' },
  { code: '4411', description: 'Steamship and Cruise Lines', category: 'Travel' },
  { code: '4457', description: 'Boat Rentals and Leasing', category: 'Travel' },
  { code: '4468', description: 'Marinas, Marine Service, and Supplies', category: 'Travel' },
  { code: '4511', description: 'Airlines and Air Carriers', category: 'Airlines', riskLevel: 'restricted' },
  { code: '4582', description: 'Airports, Flying Fields, and Airport Terminals', category: 'Transportation' },
  { code: '4722', description: 'Travel Agencies and Tour Operators', category: 'Travel' },
  { code: '4723', description: 'Tour Operators', category: 'Travel' },
  { code: '4784', description: 'Tolls and Bridge Fees', category: 'Transportation' },
  { code: '4789', description: 'Transportation Services - Not Elsewhere Classified', category: 'Transportation' },

  // ============================================================
  // Utilities (4812-4900)
  // ============================================================
  { code: '4812', description: 'Telecommunication Equipment and Telephone Sales', category: 'Utilities' },
  { code: '4813', description: 'Telecommunication Services', category: 'Utilities' },
  { code: '4814', description: 'Telecommunication Services', category: 'Utilities' },
  { code: '4815', description: 'Monthly Summary Telephone Charges', category: 'Utilities' },
  { code: '4816', description: 'Computer Network/Information Services', category: 'Digital Goods', riskLevel: 'high-risk' },
  { code: '4821', description: 'Telegraph Services', category: 'Utilities' },
  { code: '4829', description: 'Wire Transfers and Money Orders', category: 'Financial' },
  { code: '4899', description: 'Cable, Satellite, and Other Pay Television and Radio Services', category: 'Utilities' },
  { code: '4900', description: 'Utilities - Electric, Gas, Water, and Sanitary', category: 'Utilities' },

  // ============================================================
  // Wholesale/Retail (5000-5099)
  // ============================================================
  { code: '5013', description: 'Motor Vehicle Supplies and New Parts', category: 'Wholesale' },
  { code: '5021', description: 'Office and Commercial Furniture', category: 'Wholesale' },
  { code: '5039', description: 'Construction Materials - Not Elsewhere Classified', category: 'Wholesale' },
  { code: '5044', description: 'Photographic, Photocopy, Microfilm Equipment and Supplies', category: 'Wholesale' },
  { code: '5045', description: 'Computers and Computer Peripherals and Software', category: 'Wholesale' },
  { code: '5046', description: 'Commercial Equipment - Not Elsewhere Classified', category: 'Wholesale' },
  { code: '5047', description: 'Dental/Laboratory/Medical/Ophthalmic Hospital Equipment and Supplies', category: 'Wholesale' },
  { code: '5051', description: 'Metal Service Centers and Offices', category: 'Wholesale' },
  { code: '5065', description: 'Electrical Parts and Equipment', category: 'Wholesale' },
  { code: '5072', description: 'Hardware Equipment and Supplies', category: 'Wholesale' },
  { code: '5074', description: 'Plumbing and Heating Equipment and Supplies', category: 'Wholesale' },
  { code: '5085', description: 'Industrial Supplies - Not Elsewhere Classified', category: 'Wholesale' },
  { code: '5094', description: 'Precious Stones and Metals, Watches and Jewelry', category: 'Wholesale', riskLevel: 'restricted' },
  { code: '5099', description: 'Durable Goods - Not Elsewhere Classified', category: 'Wholesale' },
  { code: '5111', description: 'Stationery, Office Supplies, Printing, and Writing Paper', category: 'Wholesale' },
  { code: '5122', description: 'Drugs, Drug Proprietaries, and Druggist Sundries', category: 'Wholesale', riskLevel: 'restricted' },
  { code: '5131', description: 'Piece Goods, Notions, and Other Dry Goods', category: 'Wholesale' },
  { code: '5137', description: 'Men\'s, Women\'s, and Children\'s Uniforms and Commercial Clothing', category: 'Wholesale' },
  { code: '5139', description: 'Commercial Footwear', category: 'Wholesale' },
  { code: '5169', description: 'Chemicals and Allied Products - Not Elsewhere Classified', category: 'Wholesale' },
  { code: '5172', description: 'Petroleum and Petroleum Products', category: 'Wholesale' },
  { code: '5192', description: 'Books, Periodicals, and Newspapers', category: 'Wholesale' },
  { code: '5193', description: 'Florists\' Supplies, Nursery Stock, and Flowers', category: 'Wholesale' },
  { code: '5198', description: 'Paints, Varnishes, and Supplies', category: 'Wholesale' },
  { code: '5199', description: 'Nondurable Goods - Not Elsewhere Classified', category: 'Wholesale' },

  // ============================================================
  // Retail - Home/Building (5200-5299)
  // ============================================================
  { code: '5200', description: 'Home Supply Warehouse Stores', category: 'Retail' },
  { code: '5211', description: 'Lumber and Building Materials Stores', category: 'Retail' },
  { code: '5231', description: 'Glass, Paint, and Wallpaper Stores', category: 'Retail' },
  { code: '5251', description: 'Hardware Stores', category: 'Retail' },
  { code: '5261', description: 'Nurseries and Lawn and Garden Supply Stores', category: 'Retail' },
  { code: '5271', description: 'Mobile Home Dealers', category: 'Retail' },

  // ============================================================
  // Retail - General Merchandise (5300-5399)
  // ============================================================
  { code: '5300', description: 'General Merchandise Stores', category: 'Retail' },
  { code: '5309', description: 'Duty-Free Stores', category: 'Retail' },
  { code: '5310', description: 'Discount Stores', category: 'Retail' },
  { code: '5311', description: 'Department Stores', category: 'Retail' },
  { code: '5331', description: 'Variety Stores', category: 'Retail' },
  { code: '5399', description: 'General Merchandise - Not Elsewhere Classified', category: 'Retail' },

  // ============================================================
  // Retail - Food (5400-5499)
  // ============================================================
  { code: '5411', description: 'Grocery Stores and Supermarkets', category: 'Grocery' },
  { code: '5422', description: 'Freezer and Locker Meat Provisioners', category: 'Grocery' },
  { code: '5441', description: 'Candy, Nut, and Confectionery Stores', category: 'Grocery' },
  { code: '5451', description: 'Dairy Products Stores', category: 'Grocery' },
  { code: '5462', description: 'Bakeries', category: 'Grocery' },
  { code: '5499', description: 'Miscellaneous Food Stores - Convenience Stores and Specialty Markets', category: 'Grocery' },

  // ============================================================
  // Retail - Auto (5500-5599)
  // ============================================================
  { code: '5511', description: 'Car and Truck Dealers (New and Used) Sales, Service, Repairs, Parts, and Leasing', category: 'Auto' },
  { code: '5521', description: 'Car and Truck Dealers (Used Only)', category: 'Auto' },
  { code: '5531', description: 'Auto and Home Supply Stores', category: 'Auto' },
  { code: '5532', description: 'Automotive Tire Stores', category: 'Auto' },
  { code: '5533', description: 'Automotive Parts and Accessories Stores', category: 'Auto' },
  { code: '5541', description: 'Service Stations (with or without Ancillary Services)', category: 'Gas Stations' },
  { code: '5542', description: 'Automated Fuel Dispensers', category: 'Gas Stations' },
  { code: '5551', description: 'Boat Dealers', category: 'Retail' },
  { code: '5561', description: 'Camper, Recreational and Utility Trailer Dealers', category: 'Retail' },
  { code: '5571', description: 'Motorcycle Shops and Dealers', category: 'Retail' },
  { code: '5592', description: 'Motor Home Dealers', category: 'Retail' },
  { code: '5598', description: 'Snowmobile Dealers', category: 'Retail' },
  { code: '5599', description: 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers', category: 'Retail' },

  // ============================================================
  // Retail - Apparel (5600-5699)
  // ============================================================
  { code: '5611', description: 'Men\'s and Boys\' Clothing and Accessories Stores', category: 'Retail' },
  { code: '5621', description: 'Women\'s Ready-to-Wear Stores', category: 'Retail' },
  { code: '5631', description: 'Women\'s Accessory and Specialty Stores', category: 'Retail' },
  { code: '5641', description: 'Children\'s and Infants\' Wear Stores', category: 'Retail' },
  { code: '5651', description: 'Family Clothing Stores', category: 'Retail' },
  { code: '5655', description: 'Sports and Riding Apparel Stores', category: 'Retail' },
  { code: '5661', description: 'Shoe Stores', category: 'Retail' },
  { code: '5681', description: 'Furriers and Fur Shops', category: 'Retail' },
  { code: '5691', description: 'Men\'s and Women\'s Clothing Stores', category: 'Retail' },
  { code: '5697', description: 'Tailors, Seamstresses, Mending, and Alterations', category: 'Retail' },
  { code: '5698', description: 'Wig and Toupee Stores', category: 'Retail' },
  { code: '5699', description: 'Miscellaneous Apparel and Accessory Shops', category: 'Retail' },

  // ============================================================
  // Retail - Home Furnishings (5700-5799)
  // ============================================================
  { code: '5712', description: 'Furniture, Home Furnishings, and Equipment Stores (Except Appliances)', category: 'Retail' },
  { code: '5713', description: 'Floor Covering Stores', category: 'Retail' },
  { code: '5714', description: 'Drapery, Window Covering, and Upholstery Stores', category: 'Retail' },
  { code: '5718', description: 'Fireplace, Fireplace Screens, and Accessories Stores', category: 'Retail' },
  { code: '5719', description: 'Miscellaneous Home Furnishing Specialty Stores', category: 'Retail' },
  { code: '5722', description: 'Household Appliance Stores', category: 'Retail' },
  { code: '5732', description: 'Electronics Stores', category: 'Retail' },
  { code: '5733', description: 'Music Stores - Musical Instruments, Pianos, and Sheet Music', category: 'Retail' },
  { code: '5734', description: 'Computer Software Stores', category: 'Retail' },
  { code: '5735', description: 'Record Stores', category: 'Retail' },

  // ============================================================
  // Eating/Drinking (5811-5814)
  // ============================================================
  { code: '5811', description: 'Caterers', category: 'Restaurant' },
  { code: '5812', description: 'Eating Places and Restaurants', category: 'Restaurant' },
  { code: '5813', description: 'Drinking Places (Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques)', category: 'Restaurant' },
  { code: '5814', description: 'Fast Food Restaurants', category: 'Restaurant' },

  // ============================================================
  // Digital Goods (5815-5818)
  // ============================================================
  { code: '5815', description: 'Digital Goods - Media (Books, Movies, Music)', category: 'Digital Goods' },
  { code: '5816', description: 'Digital Goods - Games', category: 'Digital Goods', riskLevel: 'high-risk' },
  { code: '5817', description: 'Digital Goods - Applications (Excludes Games)', category: 'Digital Goods' },
  { code: '5818', description: 'Digital Goods - Large Digital Goods Merchant', category: 'Digital Goods' },

  // ============================================================
  // Retail - Miscellaneous (5912-5999)
  // ============================================================
  { code: '5912', description: 'Drug Stores and Pharmacies', category: 'Healthcare', riskLevel: 'high-risk' },
  { code: '5921', description: 'Package Stores - Beer, Wine, and Liquor', category: 'Retail' },
  { code: '5931', description: 'Used Merchandise and Secondhand Stores', category: 'Retail' },
  { code: '5932', description: 'Antique Shops - Sales, Repairs, and Restoration Services', category: 'Retail' },
  { code: '5933', description: 'Pawn Shops', category: 'Retail' },
  { code: '5935', description: 'Wrecking and Salvage Yards', category: 'Retail' },
  { code: '5937', description: 'Antique Reproductions', category: 'Retail' },
  { code: '5940', description: 'Bicycle Shops - Sales and Service', category: 'Retail' },
  { code: '5941', description: 'Sporting Goods Stores', category: 'Retail' },
  { code: '5942', description: 'Book Stores', category: 'Retail' },
  { code: '5943', description: 'Stationery Stores, Office and School Supply Stores', category: 'Retail' },
  { code: '5944', description: 'Jewelry Stores, Watches, Clocks, and Silverware Stores', category: 'Retail', riskLevel: 'restricted' },
  { code: '5945', description: 'Hobby, Toy, and Game Shops', category: 'Retail' },
  { code: '5946', description: 'Camera and Photographic Supply Stores', category: 'Retail' },
  { code: '5947', description: 'Gift, Card, Novelty, and Souvenir Shops', category: 'Retail' },
  { code: '5948', description: 'Luggage and Leather Goods Stores', category: 'Retail' },
  { code: '5949', description: 'Sewing, Needlework, Fabric, and Piece Goods Stores', category: 'Retail' },
  { code: '5950', description: 'Glassware and Crystal Stores', category: 'Retail' },
  { code: '5960', description: 'Direct Marketing - Insurance Services', category: 'Retail' },
  { code: '5962', description: 'Direct Marketing - Travel-Related Arrangement Services', category: 'Retail', riskLevel: 'high-risk' },
  { code: '5963', description: 'Door-to-Door Sales', category: 'Retail' },
  { code: '5964', description: 'Direct Marketing - Catalog Merchants', category: 'Retail' },
  { code: '5965', description: 'Direct Marketing - Combination Catalog and Retail Merchants', category: 'Retail' },
  { code: '5966', description: 'Direct Marketing - Outbound Telemarketing Merchants', category: 'Retail', riskLevel: 'high-risk' },
  { code: '5967', description: 'Direct Marketing - Inbound Telemarketing Merchants', category: 'Retail', riskLevel: 'high-risk' },
  { code: '5968', description: 'Direct Marketing - Continuity/Subscription Merchants', category: 'Retail' },
  { code: '5969', description: 'Direct Marketing - Other Direct Marketers', category: 'Retail' },
  { code: '5970', description: 'Artist\'s Supply and Craft Shops', category: 'Retail' },
  { code: '5971', description: 'Art Dealers and Galleries', category: 'Retail' },
  { code: '5972', description: 'Stamp and Coin Stores', category: 'Retail' },
  { code: '5973', description: 'Religious Goods Stores', category: 'Retail' },
  { code: '5975', description: 'Hearing Aids - Sales, Service, and Supply', category: 'Healthcare' },
  { code: '5976', description: 'Orthopedic Goods - Prosthetic Devices', category: 'Healthcare' },
  { code: '5977', description: 'Cosmetic Stores', category: 'Retail' },
  { code: '5978', description: 'Typewriter Stores - Sales, Rentals, and Service', category: 'Retail' },
  { code: '5983', description: 'Fuel Dealers - Fuel Oil, Wood, Coal, and Liquefied Petroleum', category: 'Retail' },
  { code: '5992', description: 'Florists', category: 'Retail' },
  { code: '5993', description: 'Cigar Stores and Stands', category: 'Retail', riskLevel: 'high-risk' },
  { code: '5994', description: 'Newsstand and Newsdealers', category: 'Retail' },
  { code: '5995', description: 'Pet Shops, Pet Food, and Supplies', category: 'Retail' },
  { code: '5996', description: 'Swimming Pools - Sales, Service, and Supplies', category: 'Retail' },
  { code: '5997', description: 'Electric Razor Stores - Sales and Service', category: 'Retail' },
  { code: '5998', description: 'Tent and Awning Shops', category: 'Retail' },
  { code: '5999', description: 'Miscellaneous and Specialty Retail Stores', category: 'Retail' },

  // ============================================================
  // Financial Services (6010-6513)
  // ============================================================
  { code: '6010', description: 'Financial Institutions - Manual Cash Disbursements', category: 'Financial' },
  { code: '6011', description: 'Financial Institutions - Automated Cash Disbursements', category: 'Financial' },
  { code: '6012', description: 'Financial Institutions - Merchandise and Services', category: 'Financial' },
  { code: '6051', description: 'Non-Financial Institutions - Foreign Currency, Money Orders, and Travelers Cheques', category: 'Financial' },
  { code: '6211', description: 'Security Brokers/Dealers', category: 'Financial' },
  { code: '6300', description: 'Insurance Sales, Underwriting, and Premiums', category: 'Financial' },
  { code: '6381', description: 'Insurance Premiums', category: 'Financial' },
  { code: '6399', description: 'Insurance - Not Elsewhere Classified', category: 'Financial' },
  { code: '6513', description: 'Real Estate Agents and Managers - Rentals', category: 'Professional Services' },

  // ============================================================
  // Hotels and Services (7011-7299)
  // ============================================================
  { code: '7011', description: 'Lodging - Hotels, Motels, and Resorts', category: 'Hotels' },
  { code: '7012', description: 'Timeshares', category: 'Hotels', riskLevel: 'restricted' },
  { code: '7032', description: 'Sporting and Recreational Camps', category: 'Entertainment' },
  { code: '7033', description: 'Trailer Parks and Campgrounds', category: 'Travel' },
  { code: '7210', description: 'Laundry, Cleaning, and Garment Services', category: 'Other' },
  { code: '7211', description: 'Laundry Services - Family and Commercial', category: 'Other' },
  { code: '7216', description: 'Dry Cleaners', category: 'Other' },
  { code: '7217', description: 'Carpet and Upholstery Cleaning', category: 'Other' },
  { code: '7221', description: 'Photographic Studios', category: 'Professional Services' },
  { code: '7230', description: 'Beauty and Barber Shops', category: 'Other' },
  { code: '7251', description: 'Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops', category: 'Other' },
  { code: '7261', description: 'Funeral Services and Crematories', category: 'Professional Services' },
  { code: '7273', description: 'Dating and Escort Services', category: 'Other', riskLevel: 'high-risk' },
  { code: '7276', description: 'Tax Preparation Services', category: 'Professional Services' },
  { code: '7277', description: 'Counseling Services - Debt, Marriage, Personal', category: 'Professional Services' },
  { code: '7278', description: 'Buying and Shopping Services and Clubs', category: 'Other' },
  { code: '7296', description: 'Clothing Rental - Costumes, Uniforms, and Formal Wear', category: 'Retail' },
  { code: '7297', description: 'Massage Parlors', category: 'Other' },
  { code: '7298', description: 'Health and Beauty Spas', category: 'Other' },
  { code: '7299', description: 'Miscellaneous Recreation Services - Not Elsewhere Classified', category: 'Other' },

  // ============================================================
  // Business Services (7311-7399)
  // ============================================================
  { code: '7311', description: 'Advertising Services', category: 'Professional Services' },
  { code: '7321', description: 'Consumer Credit Reporting Agencies', category: 'Professional Services' },
  { code: '7332', description: 'Blueprinting and Photocopying Services', category: 'Professional Services' },
  { code: '7333', description: 'Commercial Photography, Art, and Graphics', category: 'Professional Services' },
  { code: '7338', description: 'Quick Copy, Reproduction, and Blueprinting Services', category: 'Professional Services' },
  { code: '7339', description: 'Stenographic and Secretarial Support Services', category: 'Professional Services' },
  { code: '7342', description: 'Exterminating and Disinfecting Services', category: 'Professional Services' },
  { code: '7349', description: 'Cleaning, Maintenance, and Janitorial Services', category: 'Professional Services' },
  { code: '7361', description: 'Employment Agencies and Temporary Help Services', category: 'Professional Services' },
  { code: '7372', description: 'Computer Programming, Data Processing, and Integrated Systems Design', category: 'Professional Services' },
  { code: '7375', description: 'Information Retrieval Services', category: 'Professional Services' },
  { code: '7379', description: 'Computer Maintenance and Repair Services - Not Elsewhere Classified', category: 'Professional Services' },
  { code: '7392', description: 'Management, Consulting, and Public Relations Services', category: 'Professional Services' },
  { code: '7393', description: 'Detective Agencies, Protective Agencies, and Security Services', category: 'Professional Services' },
  { code: '7394', description: 'Equipment, Tool, Furniture, and Appliance Rental and Leasing', category: 'Professional Services' },
  { code: '7395', description: 'Photofinishing Laboratories and Photo Developing', category: 'Professional Services' },
  { code: '7399', description: 'Business Services - Not Elsewhere Classified', category: 'Professional Services' },

  // ============================================================
  // Auto Services (7511-7549)
  // ============================================================
  { code: '7511', description: 'Truck Stop', category: 'Auto' },
  { code: '7512', description: 'Automobile Rental Agency', category: 'Auto' },
  { code: '7513', description: 'Truck and Utility Trailer Rentals', category: 'Auto' },
  { code: '7519', description: 'Motor Home and Recreational Vehicle Rentals', category: 'Auto' },
  { code: '7523', description: 'Parking Lots and Garages', category: 'Auto' },
  { code: '7531', description: 'Automotive Body Repair Shops', category: 'Auto' },
  { code: '7534', description: 'Tire Retreading and Repair Shops', category: 'Auto' },
  { code: '7535', description: 'Automotive Paint Shops', category: 'Auto' },
  { code: '7538', description: 'Automotive Service Shops (Non-Dealer)', category: 'Auto' },
  { code: '7542', description: 'Car Washes', category: 'Auto' },
  { code: '7549', description: 'Towing Services', category: 'Auto' },

  // ============================================================
  // Repair Services (7622-7699)
  // ============================================================
  { code: '7622', description: 'Electronics Repair Shops', category: 'Other' },
  { code: '7623', description: 'Air Conditioning and Refrigeration Repair Shops', category: 'Other' },
  { code: '7629', description: 'Electrical and Small Appliance Repair Shops', category: 'Other' },
  { code: '7631', description: 'Watch, Clock, and Jewelry Repair', category: 'Other' },
  { code: '7641', description: 'Furniture - Reupholstery, Repair, and Refinishing', category: 'Other' },
  { code: '7692', description: 'Welding Services', category: 'Other' },
  { code: '7699', description: 'Miscellaneous Repair Shops and Related Services', category: 'Other' },

  // ============================================================
  // Entertainment/Recreation (7800-7999)
  // ============================================================
  { code: '7800', description: 'Government-Owned Lotteries', category: 'Entertainment' },
  { code: '7801', description: 'Government-Licensed Online Casinos (Online Gambling)', category: 'Entertainment' },
  { code: '7802', description: 'Government-Licensed Horse/Dog Racing', category: 'Entertainment' },
  { code: '7829', description: 'Motion Picture and Video Tape Production and Distribution', category: 'Entertainment' },
  { code: '7832', description: 'Motion Picture Theaters', category: 'Entertainment' },
  { code: '7841', description: 'Video Tape Rental Stores', category: 'Entertainment', riskLevel: 'restricted' },
  { code: '7911', description: 'Dance Halls, Studios, and Schools', category: 'Entertainment' },
  { code: '7922', description: 'Theatrical Producers (Except Motion Pictures) and Ticket Agencies', category: 'Entertainment' },
  { code: '7929', description: 'Bands, Orchestras, and Miscellaneous Entertainers', category: 'Entertainment' },
  { code: '7932', description: 'Billiard and Pool Establishments', category: 'Entertainment' },
  { code: '7933', description: 'Bowling Alleys', category: 'Entertainment' },
  { code: '7941', description: 'Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoters', category: 'Entertainment' },
  { code: '7991', description: 'Tourist Attractions and Exhibits', category: 'Entertainment' },
  { code: '7992', description: 'Public Golf Courses', category: 'Entertainment' },
  { code: '7993', description: 'Video Amusement Game Supplies', category: 'Entertainment' },
  { code: '7994', description: 'Video Game Arcades and Establishments', category: 'Entertainment' },
  { code: '7995', description: 'Betting, Casino Gambling, including Lottery Tickets', category: 'Entertainment', riskLevel: 'high-risk' },
  { code: '7996', description: 'Amusement Parks, Circuses, Carnivals, and Fortune Tellers', category: 'Entertainment' },
  { code: '7997', description: 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses', category: 'Entertainment' },
  { code: '7998', description: 'Aquariums, Seaquariums, Dolphinariums, and Zoos', category: 'Entertainment' },
  { code: '7999', description: 'Recreation Services - Not Elsewhere Classified', category: 'Entertainment' },

  // ============================================================
  // Professional Services - Healthcare (8011-8099)
  // ============================================================
  { code: '8011', description: 'Doctors and Physicians - Not Elsewhere Classified', category: 'Healthcare' },
  { code: '8021', description: 'Dentists and Orthodontists', category: 'Healthcare' },
  { code: '8031', description: 'Osteopaths', category: 'Healthcare' },
  { code: '8041', description: 'Chiropractors', category: 'Healthcare' },
  { code: '8042', description: 'Optometrists and Ophthalmologists', category: 'Healthcare' },
  { code: '8043', description: 'Opticians, Optical Goods, and Eyeglasses', category: 'Healthcare' },
  { code: '8049', description: 'Podiatrists and Chiropodists', category: 'Healthcare' },
  { code: '8050', description: 'Nursing and Personal Care Facilities', category: 'Healthcare' },
  { code: '8062', description: 'Hospitals', category: 'Healthcare' },
  { code: '8071', description: 'Medical and Dental Laboratories', category: 'Healthcare' },
  { code: '8099', description: 'Health Practitioners and Medical Services - Not Elsewhere Classified', category: 'Healthcare' },

  // ============================================================
  // Professional Services - Legal/Education (8111-8299)
  // ============================================================
  { code: '8111', description: 'Legal Services and Attorneys', category: 'Professional Services' },
  { code: '8211', description: 'Elementary and Secondary Schools', category: 'Education' },
  { code: '8220', description: 'Colleges, Universities, Professional Schools, and Junior Colleges', category: 'Education' },
  { code: '8241', description: 'Correspondence Schools', category: 'Education' },
  { code: '8244', description: 'Business and Secretarial Schools', category: 'Education' },
  { code: '8249', description: 'Vocational and Trade Schools', category: 'Education' },
  { code: '8299', description: 'Schools and Educational Services - Not Elsewhere Classified', category: 'Education' },

  // ============================================================
  // Professional Services - Organizations (8351-8699)
  // ============================================================
  { code: '8351', description: 'Child Care Services', category: 'Professional Services' },
  { code: '8398', description: 'Charitable and Social Service Organizations', category: 'Non-Profit' },
  { code: '8641', description: 'Civic, Social, and Fraternal Associations', category: 'Non-Profit' },
  { code: '8651', description: 'Political Organizations', category: 'Non-Profit' },
  { code: '8661', description: 'Religious Organizations', category: 'Non-Profit' },
  { code: '8675', description: 'Automobile Associations', category: 'Other' },
  { code: '8699', description: 'Membership Organizations - Not Elsewhere Classified', category: 'Non-Profit' },

  // ============================================================
  // Professional Services - Testing/Engineering (8734-8999)
  // ============================================================
  { code: '8734', description: 'Testing Laboratories (Non-Medical)', category: 'Professional Services' },
  { code: '8911', description: 'Architectural, Engineering, and Surveying Services', category: 'Professional Services' },
  { code: '8931', description: 'Accounting, Auditing, and Bookkeeping Services', category: 'Professional Services' },
  { code: '8999', description: 'Professional Services - Not Elsewhere Classified', category: 'Professional Services' },

  // ============================================================
  // Government (9000-9999)
  // ============================================================
  { code: '9211', description: 'Court Costs, Including Alimony and Child Support', category: 'Government' },
  { code: '9222', description: 'Fines', category: 'Government' },
  { code: '9223', description: 'Bail and Bond Payments', category: 'Government' },
  { code: '9311', description: 'Tax Payments', category: 'Government' },
  { code: '9399', description: 'Government Services - Not Elsewhere Classified', category: 'Government' },
  { code: '9402', description: 'Postal Services - Government Only', category: 'Government' },
  { code: '9405', description: 'Intra-Government Purchases - Government Only', category: 'Government' },
  { code: '9700', description: 'Automated Referral Service', category: 'Government' },
  { code: '9701', description: 'Visa Check/MasterMoney', category: 'Government' },
  { code: '9702', description: 'Emergency Services (GCAS)', category: 'Government' },
  { code: '9751', description: 'UK Supermarkets, Electronic Hot File', category: 'Government' },
  { code: '9752', description: 'UK Petrol Stations, Electronic Hot File', category: 'Government' },
  { code: '9950', description: 'Intra-Company Purchases', category: 'Government' },
];

/**
 * Lookup an MCC code by its numeric code string.
 */
export function getMCCByCode(code: string): MCCCode | undefined {
  return MCC_CODES.find((mcc) => mcc.code === code);
}

/**
 * Search MCC codes by description keyword (case-insensitive).
 */
export function searchMCCCodes(query: string): MCCCode[] {
  const lower = query.toLowerCase();
  return MCC_CODES.filter(
    (mcc) =>
      mcc.description.toLowerCase().includes(lower) ||
      mcc.code.includes(lower)
  );
}

/**
 * Get all MCC codes for a given category.
 */
export function getMCCByCategory(category: string): MCCCode[] {
  return MCC_CODES.filter((mcc) => mcc.category === category);
}

/**
 * Get all high-risk MCC codes.
 */
export function getHighRiskMCCs(): MCCCode[] {
  return MCC_CODES.filter((mcc) => mcc.riskLevel === 'high-risk');
}

/**
 * Get all restricted MCC codes.
 */
export function getRestrictedMCCs(): MCCCode[] {
  return MCC_CODES.filter((mcc) => mcc.riskLevel === 'restricted');
}

/**
 * Get all unique categories in the MCC list.
 */
export function getMCCCategories(): string[] {
  return [...new Set(MCC_CODES.map((mcc) => mcc.category))].sort();
}
