import { PDFDocument, StandardFonts, rgb, PDFPage, PDFFont } from "pdf-lib";

// ── Helpers ──────────────────────────────────────────────────────────────

const PAGE_W = 612; // Letter width in points
const PAGE_H = 792; // Letter height
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

function val(v: any): string {
  if (v === null || v === undefined || v === "") return "\u2014";
  return String(v);
}

function titleCase(s: string | null): string {
  if (!s) return "\u2014";
  return s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function maskLast4(s: string | null): string {
  if (!s) return "\u2014";
  return "****" + s.slice(-4);
}

/** Draw text that wraps, return new Y position. */
function drawWrapped(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  maxWidth: number,
  color = rgb(0.2, 0.2, 0.2)
): number {
  const words = text.split(" ");
  let line = "";
  let curY = y;
  for (const word of words) {
    const test = line ? line + " " + word : word;
    if (font.widthOfTextAtSize(test, size) > maxWidth && line) {
      page.drawText(line, { x, y: curY, size, font, color });
      curY -= size + 4;
      line = word;
    } else {
      line = test;
    }
  }
  if (line) {
    page.drawText(line, { x, y: curY, size, font, color });
    curY -= size + 4;
  }
  return curY;
}

// ── Types ────────────────────────────────────────────────────────────────

export interface SignatureCertParams {
  businessLegalName: string;
  dbaName: string;
  signerName: string;
  signerEmail: string;
  signedAt: string; // ISO string
  signerIp: string;
  signerUserAgent: string;
  signatureDataBase64: string; // data:image/png;base64,...
}

export interface MpaSummaryParams {
  deal: any;
  owners: any[];
  lead: any;
  partnerName: string | null;
  signerName: string;
  signedAt: string;
  signatureDataBase64: string;
}

// ── Signature Certificate ────────────────────────────────────────────────

export async function generateSignatureCertificate(
  params: SignatureCertParams
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_W, PAGE_H]);
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const dark = rgb(0.12, 0.14, 0.17);
  const gray = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.05, 0.65, 0.35);

  let y = PAGE_H - MARGIN;

  // Header
  page.drawText("SPLITS", { x: MARGIN, y, size: 20, font: helveticaBold, color: accent });
  y -= 14;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 30;

  // Title
  page.drawText("Electronic Signature Certificate", { x: MARGIN, y, size: 18, font: helveticaBold, color: dark });
  y -= 30;

  // Field rows
  const field = (label: string, value: string) => {
    page.drawText(label, { x: MARGIN, y, size: 9, font: helveticaBold, color: gray });
    y -= 14;
    y = drawWrapped(page, value, MARGIN, y, helvetica, 11, CONTENT_W, dark);
    y -= 8;
  };

  field("Document", "Merchant Processing Application");
  field("Business", `${val(params.businessLegalName)} DBA ${val(params.dbaName)}`);
  field("Signer", `${params.signerName} (${params.signerEmail})`);
  field("Signed At", new Date(params.signedAt).toUTCString());
  field("IP Address", params.signerIp);
  field("User Agent", params.signerUserAgent);
  field("Consent", "Signer agreed to conduct this transaction electronically under the ESIGN Act.");

  // Signature image
  y -= 10;
  page.drawText("Signature", { x: MARGIN, y, size: 9, font: helveticaBold, color: gray });
  y -= 10;

  try {
    const b64 = params.signatureDataBase64.replace(/^data:image\/png;base64,/, "");
    const sigBytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    const sigImg = await doc.embedPng(sigBytes);
    const sigW = Math.min(250, CONTENT_W);
    const sigH = sigW * (sigImg.height / sigImg.width);
    page.drawImage(sigImg, { x: MARGIN, y: y - sigH, width: sigW, height: sigH });
    y -= sigH + 15;
  } catch {
    page.drawText("[Signature image could not be rendered]", { x: MARGIN, y, size: 10, font: helvetica, color: gray });
    y -= 20;
  }

  // Footer
  y = Math.min(y, MARGIN + 50);
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  y -= 14;
  drawWrapped(
    page,
    "This certificate was generated by Splits CRM and confirms the electronic signature captured above.",
    MARGIN, y, helvetica, 8, CONTENT_W, gray
  );

  return doc.save();
}

// ── MPA Summary ──────────────────────────────────────────────────────────

export async function generateMpaSummary(
  params: MpaSummaryParams
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const dark = rgb(0.12, 0.14, 0.17);
  const gray = rgb(0.4, 0.4, 0.4);
  const accent = rgb(0.05, 0.65, 0.35);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  const ensureSpace = (need: number) => {
    if (y - need < MARGIN) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - MARGIN;
    }
  };

  const sectionTitle = (title: string) => {
    ensureSpace(40);
    y -= 8;
    page.drawLine({ start: { x: MARGIN, y: y + 4 }, end: { x: PAGE_W - MARGIN, y: y + 4 }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
    y -= 6;
    page.drawText(title.toUpperCase(), { x: MARGIN, y, size: 9, font: helveticaBold, color: accent });
    y -= 18;
  };

  const row = (label: string, value: string | null | undefined) => {
    ensureSpace(20);
    page.drawText(label + ":", { x: MARGIN, y, size: 9, font: helveticaBold, color: gray });
    page.drawText(val(value), { x: MARGIN + 160, y, size: 10, font: helvetica, color: dark });
    y -= 16;
  };

  const d = params.deal || {};
  const l = params.lead || {};

  // Header
  page.drawText("SPLITS", { x: MARGIN, y, size: 20, font: helveticaBold, color: accent });
  y -= 14;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 28;

  page.drawText(`Merchant Application Summary`, { x: MARGIN, y, size: 16, font: helveticaBold, color: dark });
  y -= 18;
  page.drawText(val(d.dba_name || l.business_name), { x: MARGIN, y, size: 12, font: helvetica, color: gray });
  y -= 16;

  const meta: string[] = [];
  if (params.partnerName) meta.push("Partner: " + params.partnerName);
  if (d.sponsor_bank) meta.push("Bank: " + d.sponsor_bank);
  meta.push("Generated: " + new Date().toLocaleDateString());
  page.drawText(meta.join("  |  "), { x: MARGIN, y, size: 8, font: helvetica, color: gray });
  y -= 20;

  // ── Business Information ──
  sectionTitle("Business Information");
  row("Business Legal Name", d.business_legal_name || l.business_name);
  row("DBA Name", d.dba_name);
  row("Legal Address", [d.legal_street, d.legal_city, d.legal_state, d.legal_zip].filter(Boolean).join(", "));
  if (d.location_street) row("Location Address", [d.location_name, d.location_street, d.location_city, d.location_state, d.location_zip].filter(Boolean).join(", "));
  row("Business Phone", d.business_phone || l.phone);
  row("Business Email", d.business_email || l.email);
  row("Entity Type", titleCase(d.entity_type));
  row("EIN/ITIN", d.ein_itin);
  row("MCC Code", d.mcc_code);
  row("SIC Code", d.sic_code);
  if (d.business_start_date) row("Business Start Date", new Date(d.business_start_date + "T00:00:00").toLocaleDateString());
  if (d.annual_revenue) row("Annual Revenue", "$" + Number(d.annual_revenue).toLocaleString());
  if (d.products_services_description) row("Products/Services", d.products_services_description);

  // ── Ownership ──
  if (params.owners.length > 0) {
    sectionTitle("Principal / Owner Information");
    for (let i = 0; i < params.owners.length; i++) {
      const o = params.owners[i];
      if (i > 0) y -= 6;
      ensureSpace(80);
      if (params.owners.length > 1) {
        page.drawText(`Owner ${i + 1}`, { x: MARGIN, y, size: 9, font: helveticaBold, color: dark });
        y -= 16;
      }
      row("Name", o.full_name);
      row("Title", o.title);
      row("Ownership %", o.ownership_pct ? o.ownership_pct + "%" : null);
      row("DOB", o.dob ? new Date(o.dob + "T00:00:00").toLocaleDateString() : null);
      // SSN: show last 4 only from the ssn_encrypted field
      const ssnDisplay = o.ssn_encrypted ? "***-**-" + o.ssn_encrypted.slice(-4) : null;
      row("SSN", ssnDisplay);
      if (o.address) row("Address", [o.address, o.city, o.state, o.zip].filter(Boolean).join(", "));
      if (o.email) row("Email", o.email);
      if (o.phone) row("Phone", o.phone);
    }
  }

  // ── Processing ──
  sectionTitle("Processing Information");
  row("Monthly Volume", d.monthly_volume ? "$" + Number(d.monthly_volume).toLocaleString() : null);
  row("Average Ticket", d.average_ticket ? "$" + Number(d.average_ticket).toLocaleString() : null);
  row("High Ticket", d.high_ticket ? "$" + Number(d.high_ticket).toLocaleString() : null);
  row("Card Present %", d.cp_pct ? d.cp_pct + "%" : null);
  row("Card Not Present %", d.cnp_pct ? d.cnp_pct + "%" : null);
  if (d.monthly_transactions) row("Monthly Transactions", val(d.monthly_transactions));
  if (d.reason_for_leaving) row("Reason for Leaving", d.reason_for_leaving);

  // ── Pricing ──
  sectionTitle("Pricing");
  row("Pricing Type", titleCase(d.pricing_type));
  if (d.pricing_type === "interchange_plus") {
    row("Visa", `${d.ic_plus_visa_pct || 0}% + $${d.ic_plus_visa_txn || 0}`);
    row("MC", `${d.ic_plus_mc_pct || 0}% + $${d.ic_plus_mc_txn || 0}`);
    row("AMEX", `${d.ic_plus_amex_pct || 0}% + $${d.ic_plus_amex_txn || 0}`);
    row("Discover", `${d.ic_plus_disc_pct || 0}% + $${d.ic_plus_disc_txn || 0}`);
  }
  if (d.pricing_type === "dual_pricing") {
    row("Rate", d.dual_pricing_rate ? d.dual_pricing_rate + "%" : null);
    row("Per Txn", d.dual_pricing_txn_fee ? "$" + d.dual_pricing_txn_fee : null);
  }
  if (d.pricing_type === "flat_rate") {
    row("Rate", d.flat_rate_pct ? d.flat_rate_pct + "%" : null);
    row("Per Txn", d.flat_rate_txn_cost ? "$" + d.flat_rate_txn_cost : null);
  }
  if (d.fee_chargeback) row("Chargeback Fee", "$" + d.fee_chargeback);
  if (d.fee_retrieval) row("Retrieval Fee", "$" + d.fee_retrieval);
  if (d.monthly_fee_statement) row("Statement Fee", "$" + d.monthly_fee_statement + "/mo");
  if (d.pci_compliance_monthly) row("PCI Monthly", "$" + d.pci_compliance_monthly + "/mo");
  if (d.pci_compliance_annual) row("PCI Annual", "$" + d.pci_compliance_annual + "/yr");

  // ── Banking ──
  if (d.bank_routing || d.bank_account) {
    sectionTitle("Banking");
    if (d.bank_account_holder_name) row("Account Holder", d.bank_account_holder_name);
    row("Routing Number", maskLast4(d.bank_routing));
    row("Account Number", maskLast4(d.bank_account));
    if (d.bank_account_type) row("Account Type", titleCase(d.bank_account_type));
  }

  // ── Equipment ──
  const hw = d.hardware_items || [];
  const sw = d.software_items || [];
  if (hw.length > 0 || sw.length > 0) {
    sectionTitle("Equipment & Software");
    for (const item of hw) {
      ensureSpace(18);
      const desc = `${item.quantity || 1}x ${item.model || item.type || "Hardware"}${item.free === "yes" ? " (Free)" : item.cost ? " ($" + item.cost + ")" : ""}`;
      page.drawText(desc, { x: MARGIN, y, size: 10, font: helvetica, color: dark });
      y -= 16;
    }
    for (const item of sw) {
      ensureSpace(18);
      const desc = `${item.name || "Software"}${item.type ? " (" + item.type + ")" : ""}${item.monthly_cost ? " \u2014 $" + item.monthly_cost + "/mo" : ""}`;
      page.drawText(desc, { x: MARGIN, y, size: 10, font: helvetica, color: dark });
      y -= 16;
    }
  }

  // ── Compliance ──
  if (d.pci_compliance_status || d.beneficial_ownership_certified) {
    sectionTitle("Compliance");
    if (d.pci_compliance_status) row("PCI Status", titleCase(d.pci_compliance_status));
    if (d.pci_compliance_vendor) row("PCI Vendor", d.pci_compliance_vendor);
    if (d.beneficial_ownership_certified) row("Beneficial Ownership Certified", new Date(d.beneficial_ownership_certified + "T00:00:00").toLocaleDateString());
  }

  // ── Signature ──
  ensureSpace(120);
  y -= 10;
  page.drawLine({ start: { x: MARGIN, y: y + 4 }, end: { x: PAGE_W - MARGIN, y: y + 4 }, thickness: 0.5, color: rgb(0.85, 0.85, 0.85) });
  y -= 10;

  try {
    const b64 = params.signatureDataBase64.replace(/^data:image\/png;base64,/, "");
    const sigBytes = Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
    const sigImg = await doc.embedPng(sigBytes);
    const sigW = Math.min(200, CONTENT_W);
    const sigH = sigW * (sigImg.height / sigImg.width);
    page.drawImage(sigImg, { x: MARGIN, y: y - sigH, width: sigW, height: sigH });
    y -= sigH + 10;
  } catch {
    y -= 10;
  }

  page.drawText(
    `Electronically signed by ${params.signerName} on ${new Date(params.signedAt).toUTCString()}`,
    { x: MARGIN, y, size: 9, font: helvetica, color: gray }
  );

  return doc.save();
}
